name: Maven CI/CD Workflow

on:
  push:
    branches: 
      - main
      - redesign-for-elva
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: 'maven'

      - name: Build DCM4CHE
        run: |
          cd dcm4che-master/
          mvn install

      - name: Build DCM4CHE Arc Lang
        run: |
          cd dcm4chee-arc-lang-master/
          mvn install

      - name: Build DCM4CHE Arc UI 2
        run: |
          cd dcm4chee-arc-light-master/dcm4chee-arc-ui2
          mvn clean install

      - name: Upload WAR file
        uses: actions/upload-artifact@v3
        with:
          name: dcm4chee-arc-ui2-war
          path: dcm4chee-arc-light-master/dcm4chee-arc-ui2/target/*.war